---
- name: Install MySQL, create database, user, and grant permissions
  hosts: web
  vars_files:
    - secrets.yml
  tasks:
    - name: Install MySQL
      become: yes
      package:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is enabled and started
      become: yes
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Create database named 'ivolve'
      become: yes
      mysql_db:
        name: ivolve
        state: present

    - name: Create MySQL user 'ivolve' with password from Ansible Vault
      become: yes
      mysql_user:
        name: ivolve
        password: "{{ database_password }}"
        priv: '*.*:ALL'
        state: present

    - name: Grant user 'ivolve' permission to create tables in 'ivolve' database
      become: yes
      mysql_user:
        name: ivolve
        password: "{{ database_password }}"
        priv: 'ivolve.*:CREATE'
        state: present


