---
- name: Create ivolve file
  hosts: all
  remote_user: ubuntu
  become: yes  # This allows Ansible to execute tasks with sudo privileges, if required
  
  tasks:
    - name: Create the ivolve file
      ansible.builtin.file:
        path: /home/ubuntu/ivolve  # Specify the path where you want to create the ivolve file
        state: touch  # Ensure the file exists, creating it if necessary

