# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: nti

# Apply resource quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nti-resource-quota
  namespace: nti
spec:
  hard:
    pods: "5"
    cpu: "2"
    memory: 2Gi

