---
- name: Configure Apache Web Server
  hosts: web
  become: yes

  tasks:
    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: present

    - name: Ensure Apache service is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Deploy sample website
      copy:
        content: "Welcome to my sample website!"
        dest: /var/www/html/index.html

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

