apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'sleep 10']
      containers:
      - name: jenkins
        image: your-jenkins-image
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
        livenessProbe:
          httpGet:
            path: /login
            port: 8080

